
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Configuracion;

import java_cup.runtime.*;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Sintactico_Configuracion extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Sintactico_Configuracion() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Sintactico_Configuracion(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintactico_Configuracion(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\033\000\002\002\004\000\002\021\003\000\002\002" +
    "\011\000\002\010\005\000\002\010\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\007\003\000" +
    "\002\003\005\000\002\004\005\000\002\005\005\000\002" +
    "\006\007\000\002\011\005\000\002\011\003\000\002\014" +
    "\003\000\002\014\003\000\002\017\007\000\002\020\007" +
    "\000\002\012\005\000\002\012\003\000\002\013\005\000" +
    "\002\013\003\000\002\015\003\000\002\015\003\000\002" +
    "\016\003\000\002\016\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\073\000\004\004\006\001\002\000\004\002\075\001" +
    "\002\000\004\002\000\001\002\000\004\010\007\001\002" +
    "\000\004\007\010\001\002\000\004\004\011\001\002\000" +
    "\012\013\021\014\013\015\017\020\020\001\002\000\006" +
    "\005\ufffc\006\ufffc\001\002\000\004\007\073\001\002\000" +
    "\006\005\070\006\067\001\002\000\006\005\ufffa\006\ufffa" +
    "\001\002\000\006\005\ufffd\006\ufffd\001\002\000\004\007" +
    "\030\001\002\000\004\007\026\001\002\000\004\007\024" +
    "\001\002\000\006\005\ufffb\006\ufffb\001\002\000\006\005" +
    "\ufff9\006\ufff9\001\002\000\004\017\025\001\002\000\006" +
    "\005\ufff8\006\ufff8\001\002\000\004\017\027\001\002\000" +
    "\006\005\ufff7\006\ufff7\001\002\000\004\004\031\001\002" +
    "\000\006\011\037\012\032\001\002\000\004\007\056\001" +
    "\002\000\006\005\ufff1\006\ufff1\001\002\000\006\005\ufff3" +
    "\006\ufff3\001\002\000\006\005\054\006\053\001\002\000" +
    "\006\005\ufff2\006\ufff2\001\002\000\004\007\040\001\002" +
    "\000\004\004\041\001\002\000\006\016\042\020\020\001" +
    "\002\000\004\007\051\001\002\000\006\005\uffe8\006\uffe8" +
    "\001\002\000\006\005\uffeb\006\uffeb\001\002\000\006\005" +
    "\047\006\046\001\002\000\006\016\042\020\020\001\002" +
    "\000\006\005\uffef\006\uffef\001\002\000\006\005\uffec\006" +
    "\uffec\001\002\000\004\017\052\001\002\000\006\005\uffe7" +
    "\006\uffe7\001\002\000\006\011\037\012\032\001\002\000" +
    "\006\005\ufff5\006\ufff5\001\002\000\006\005\ufff4\006\ufff4" +
    "\001\002\000\004\004\057\001\002\000\010\011\037\012" +
    "\032\020\020\001\002\000\006\005\uffed\006\uffed\001\002" +
    "\000\006\005\065\006\064\001\002\000\006\005\uffe9\006" +
    "\uffe9\001\002\000\006\005\uffea\006\uffea\001\002\000\010" +
    "\011\037\012\032\020\020\001\002\000\006\005\ufff0\006" +
    "\ufff0\001\002\000\006\005\uffee\006\uffee\001\002\000\012" +
    "\013\021\014\013\015\017\020\020\001\002\000\004\005" +
    "\071\001\002\000\004\002\uffff\001\002\000\006\005\ufffe" +
    "\006\ufffe\001\002\000\004\017\074\001\002\000\006\005" +
    "\ufff6\006\ufff6\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\073\000\006\002\004\021\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\016\003\011\004\021\005\014\006" +
    "\022\007\015\010\013\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\011\034\014\033\017\035\020\032\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\004\042\013\044\016\043\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\004\042\016\047\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\014\054\017\035\020\032\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\004" +
    "\062\012\060\014\061\015\057\017\035\020\032\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\014\004\062\014\061\015\065\017\035" +
    "\020\032\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\003\011\004\021\005\014\006\022\007\071\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintactico_Configuracion$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintactico_Configuracion$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintactico_Configuracion$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	public static ArrayList<String> ErroresSintacticos = new ArrayList<>();
    public Proyecto arbol_configuracion;
    public String salida = "" ; 
       
    public void syntax_error(Symbol s)
    {
        System.err.println("El analizador se recupero tras el error\nError en la Línea " + (s.left+1) +" Columna "+(s.right+1)+ ". Identificador "
        +s.value + " no reconocido." );  
        ErroresSintacticos.add("El analizador se recupero tras el error\nError en la Línea " + (s.left+1) +" Columna "+(s.right+1)+ ". Identificador "
        +s.value + " no reconocido." );
    }

   ////////////////////////////
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
        System.err.println("El analizador No se recupero tras el error\nError en la Línea " + (s.left+1)+ " Columna "+(s.right+1)+". Identificador " +
        s.value + " no reconocido.");            
    }
    
    public void setSalida(String cadena)
    {
        salida = cadena;
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Sintactico_Configuracion$actions {
  private final Sintactico_Configuracion parser;

  /** Constructor */
  CUP$Sintactico_Configuracion$actions(Sintactico_Configuracion parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Sintactico_Configuracion$do_action_part00000000(
    int                        CUP$Sintactico_Configuracion$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico_Configuracion$parser,
    java.util.Stack            CUP$Sintactico_Configuracion$stack,
    int                        CUP$Sintactico_Configuracion$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintactico_Configuracion$result;

      /* select the action based on the action number */
      switch (CUP$Sintactico_Configuracion$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= S EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-1)).value;
		RESULT = start_val;
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintactico_Configuracion$parser.done_parsing();
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // S ::= PROYECTO 
            {
              String RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Proyecto a = (Proyecto)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 arbol_configuracion=a; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("S",15, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // PROYECTO ::= Tllave_a Tproyecto Tdospuntos Tllave_a R1 Tllave_c Tllave_c 
            {
              Proyecto RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).right;
		ArrayList<Contenido> a = (ArrayList<Contenido>)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).value;
		 RESULT = new Proyecto(a); 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("PROYECTO",0, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-6)), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // R1 ::= R1 Tcoma CONTENIDO 
            {
              ArrayList<Contenido> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).right;
		ArrayList<Contenido> a = (ArrayList<Contenido>)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido b = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 a.add(b); RESULT = a; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("R1",6, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // R1 ::= CONTENIDO 
            {
              ArrayList<Contenido> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido a = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		ArrayList<Contenido> lst = new ArrayList<>(); lst.add(a);RESULT = lst; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("R1",6, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // CONTENIDO ::= RUTA 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido a = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 RESULT = a; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("CONTENIDO",5, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // CONTENIDO ::= NOMBRE 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido a = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 RESULT = a; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("CONTENIDO",5, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // CONTENIDO ::= CORRER 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido a = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 RESULT = a; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("CONTENIDO",5, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // CONTENIDO ::= CONFIGURACION 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido a = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 RESULT = a; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("CONTENIDO",5, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // RUTA ::= Truta Tdospuntos Tcadena 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 RESULT= new Contenido(Etiqueta.RUTA,a); 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("RUTA",1, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // NOMBRE ::= Tnombre Tdospuntos Tcadena 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 RESULT= new Contenido(Etiqueta.NOMBRE,a); 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("NOMBRE",2, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // CORRER ::= Tcorrer Tdospuntos Tcadena 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 RESULT= new Contenido(Etiqueta.CORRER,a); 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("CORRER",3, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // CONFIGURACION ::= Tconfiguracion Tdospuntos Tllave_a R2 Tllave_c 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-1)).right;
		ArrayList<Contenido> a = (ArrayList<Contenido>)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-1)).value;
		 RESULT= new Contenido(Etiqueta.CONFIGURACION,a); 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("CONFIGURACION",4, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // R2 ::= R2 Tcoma R3 
            {
              ArrayList<Contenido> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).right;
		ArrayList<Contenido> a = (ArrayList<Contenido>)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido b = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 a.add(b); RESULT = a; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("R2",7, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // R2 ::= R3 
            {
              ArrayList<Contenido> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido a = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		ArrayList<Contenido> lst = new ArrayList<>(); lst.add(a);RESULT = lst; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("R2",7, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // R3 ::= CARPETA 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido a = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 RESULT = a; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("R3",10, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // R3 ::= ARCHIVO 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido a = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 RESULT = a; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("R3",10, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // CARPETA ::= Tcarpeta Tdospuntos Tllave_a R4 Tllave_c 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-1)).right;
		ArrayList<Contenido> a = (ArrayList<Contenido>)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-1)).value;
		 RESULT= new Contenido(Etiqueta.CARPETA,a); 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("CARPETA",13, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // ARCHIVO ::= Tarchivo Tdospuntos Tllave_a R6 Tllave_c 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-1)).right;
		ArrayList<Contenido> a = (ArrayList<Contenido>)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-1)).value;
		 RESULT= new Contenido(Etiqueta.ARCHIVO,a); 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("ARCHIVO",14, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-4)), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // R4 ::= R4 Tcoma R5 
            {
              ArrayList<Contenido> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).right;
		ArrayList<Contenido> a = (ArrayList<Contenido>)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido b = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 a.add(b); RESULT = a; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("R4",8, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // R4 ::= R5 
            {
              ArrayList<Contenido> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido a = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		ArrayList<Contenido> lst = new ArrayList<>(); lst.add(a);RESULT = lst; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("R4",8, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // R6 ::= R6 Tcoma R7 
            {
              ArrayList<Contenido> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).right;
		ArrayList<Contenido> a = (ArrayList<Contenido>)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido b = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 a.add(b); RESULT = a; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("R6",9, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // R6 ::= R7 
            {
              ArrayList<Contenido> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido a = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		ArrayList<Contenido> lst = new ArrayList<>(); lst.add(a);RESULT = lst; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("R6",9, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // R5 ::= NOMBRE 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido a = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 RESULT = a; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("R5",11, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // R5 ::= R3 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido a = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 RESULT = a; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("R5",11, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // R7 ::= NOMBRE 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Contenido a = (Contenido)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 RESULT = a; 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("R7",12, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // R7 ::= Tfechamod Tdospuntos Tcadena 
            {
              Contenido RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Sintactico_Configuracion$stack.peek()).value;
		 RESULT = new Contenido(Etiqueta.FECHA_MOD, a); 
              CUP$Sintactico_Configuracion$result = parser.getSymbolFactory().newSymbol("R7",12, ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.elementAt(CUP$Sintactico_Configuracion$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico_Configuracion$stack.peek()), RESULT);
            }
          return CUP$Sintactico_Configuracion$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Sintactico_Configuracion$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Sintactico_Configuracion$do_action(
    int                        CUP$Sintactico_Configuracion$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico_Configuracion$parser,
    java.util.Stack            CUP$Sintactico_Configuracion$stack,
    int                        CUP$Sintactico_Configuracion$top)
    throws java.lang.Exception
    {
              return CUP$Sintactico_Configuracion$do_action_part00000000(
                               CUP$Sintactico_Configuracion$act_num,
                               CUP$Sintactico_Configuracion$parser,
                               CUP$Sintactico_Configuracion$stack,
                               CUP$Sintactico_Configuracion$top);
    }
}

}
