
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Configuracion;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Tcoma = 4;
  public static final int Truta = 9;
  public static final int Tcadena = 13;
  public static final int Tfechamod = 12;
  public static final int Tllave_c = 3;
  public static final int Tllave_a = 2;
  public static final int Tconfiguracion = 11;
  public static final int Tdospuntos = 5;
  public static final int Tcarpeta = 8;
  public static final int EOF = 0;
  public static final int Tarchivo = 7;
  public static final int error = 1;
  public static final int Tcorrer = 10;
  public static final int Tnombre = 14;
  public static final int Tproyecto = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Tllave_a",
  "Tllave_c",
  "Tcoma",
  "Tdospuntos",
  "Tproyecto",
  "Tarchivo",
  "Tcarpeta",
  "Truta",
  "Tcorrer",
  "Tconfiguracion",
  "Tfechamod",
  "Tcadena",
  "Tnombre"
  };
}

