/* The following code was generated by JFlex 1.7.0 */

package Analizadores;

import java_cup.runtime.Symbol;




/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/Analizadores/Lexico.jflex</tt>
 */
public class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int cadena = 2;
  public static final int cadena2 = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\73\1\74\1\100\1\73\1\75\22\0\1\61\1\23\1\76"+
    "\1\55\1\0\1\22\1\11\1\77\1\17\1\20\1\3\1\2\1\21"+
    "\1\1\1\26\1\4\12\72\1\25\1\16\1\5\1\7\1\6\1\102"+
    "\1\0\6\71\1\66\1\71\1\70\4\71\1\65\3\71\1\56\2\71"+
    "\1\67\5\71\1\14\1\101\1\15\1\24\1\42\1\0\1\46\1\36"+
    "\1\33\1\32\1\27\1\51\1\54\1\34\1\50\1\62\1\63\1\40"+
    "\1\53\1\30\1\41\1\43\1\60\1\35\1\44\1\31\1\37\1\45"+
    "\1\52\1\57\1\64\1\47\1\12\1\10\1\13\7\0\1\100\113\0"+
    "\1\71\37\0\1\71\u1f36\0\1\100\1\100\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\2\1\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\10\26"+
    "\1\1\7\26\1\1\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\34\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\0\1\47\1\0"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\12\26\10\0"+
    "\5\26\1\56\5\26\3\0\5\26\1\0\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\1\0\1\47\1\0\1\65"+
    "\1\26\1\66\1\26\1\67\1\26\1\70\4\26\1\71"+
    "\15\0\1\72\1\0\4\26\1\73\1\26\1\74\4\26"+
    "\3\0\5\26\1\75\2\0\1\76\1\77\1\26\1\100"+
    "\3\26\14\0\1\101\2\0\3\26\1\102\4\26\1\103"+
    "\4\26\3\0\1\104\1\26\1\105\2\26\1\0\4\26"+
    "\1\106\1\0\1\107\1\0\1\110\1\0\1\111\1\112"+
    "\1\113\5\0\7\26\1\114\1\115\4\26\3\0\1\116"+
    "\1\117\1\120\1\121\2\26\1\0\1\26\1\122\1\26"+
    "\1\123\1\124\4\0\1\125\1\126\1\0\1\26\1\127"+
    "\2\26\1\130\1\26\1\131\1\26\1\132\2\26\3\0"+
    "\2\26\1\133\1\134\1\26\1\0\1\135\3\0\2\26"+
    "\1\136\3\26\1\137\3\0\1\140\1\26\1\141\4\0"+
    "\1\142\1\143\1\26\1\144\1\145\1\146\2\0\1\147"+
    "\1\150\3\0\1\26\1\151\3\0\1\152\1\26\3\0"+
    "\1\26\3\0\1\153\2\0\1\154\1\0\1\155\3\0"+
    "\1\156";

  private static int [] zzUnpackAction() {
    int [] result = new int[341];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\103\0\206\0\311\0\u010c\0\u014f\0\311\0\u0192"+
    "\0\u01d5\0\u0218\0\u025b\0\u029e\0\u02e1\0\311\0\311\0\311"+
    "\0\311\0\311\0\311\0\311\0\311\0\311\0\311\0\311"+
    "\0\311\0\311\0\u0324\0\u0367\0\u03aa\0\u03ed\0\u0430\0\u0473"+
    "\0\u04b6\0\u04f9\0\u053c\0\u057f\0\u05c2\0\u0605\0\u0648\0\u068b"+
    "\0\u06ce\0\u0711\0\u0754\0\u0797\0\311\0\u07da\0\311\0\311"+
    "\0\311\0\311\0\311\0\u081d\0\311\0\311\0\311\0\311"+
    "\0\311\0\311\0\311\0\311\0\311\0\u0860\0\u08a3\0\u08e6"+
    "\0\311\0\311\0\311\0\311\0\311\0\311\0\u0929\0\u096c"+
    "\0\u09af\0\u09f2\0\u0a35\0\u0a78\0\u0abb\0\u0afe\0\u0b41\0\u0b84"+
    "\0\u0bc7\0\u0c0a\0\u0c4d\0\u0c90\0\u0cd3\0\u0d16\0\u0d59\0\u0d9c"+
    "\0\u0ddf\0\u0e22\0\u0e65\0\u0ea8\0\u0eeb\0\u0473\0\u0f2e\0\u0f71"+
    "\0\u0fb4\0\u0ff7\0\u103a\0\u107d\0\u10c0\0\u1103\0\u1146\0\u1189"+
    "\0\u11cc\0\u120f\0\u1252\0\u1295\0\311\0\311\0\311\0\311"+
    "\0\311\0\311\0\u12d8\0\311\0\u131b\0\u0473\0\u135e\0\u0473"+
    "\0\u13a1\0\u0473\0\u13e4\0\u0473\0\u1427\0\u146a\0\u14ad\0\u14f0"+
    "\0\u0473\0\u1533\0\u1576\0\u15b9\0\u15fc\0\u163f\0\u1682\0\u16c5"+
    "\0\u1708\0\u174b\0\u178e\0\u17d1\0\u1814\0\u1857\0\311\0\u189a"+
    "\0\u18dd\0\u1920\0\u1963\0\u19a6\0\u0473\0\u19e9\0\u0473\0\u1a2c"+
    "\0\u1a6f\0\u1ab2\0\u1af5\0\u1b38\0\u1b7b\0\u1bbe\0\u1c01\0\u1c44"+
    "\0\u1c87\0\u1cca\0\u1d0d\0\u1295\0\u1d50\0\u1d93\0\u1dd6\0\u0473"+
    "\0\u1e19\0\u0473\0\u1e5c\0\u1e9f\0\u1ee2\0\u1f25\0\u1f68\0\u1fab"+
    "\0\u1fee\0\u2031\0\u2074\0\u20b7\0\u20fa\0\u213d\0\u2180\0\u21c3"+
    "\0\u2206\0\311\0\u2249\0\u228c\0\u22cf\0\u2312\0\u2355\0\u0473"+
    "\0\u2398\0\u23db\0\u241e\0\u2461\0\u0473\0\u24a4\0\u24e7\0\u252a"+
    "\0\u256d\0\u25b0\0\u25f3\0\u2636\0\u2679\0\u26bc\0\u0473\0\u26ff"+
    "\0\u2742\0\u2785\0\u27c8\0\u280b\0\u284e\0\u2891\0\311\0\u28d4"+
    "\0\311\0\u2917\0\311\0\u295a\0\311\0\311\0\311\0\u299d"+
    "\0\u29e0\0\u2a23\0\u2a66\0\u2aa9\0\u2aec\0\u2b2f\0\u2b72\0\u2bb5"+
    "\0\u2bf8\0\u2c3b\0\u2c7e\0\u0473\0\u0473\0\u2cc1\0\u2d04\0\u2d47"+
    "\0\u2d8a\0\u2dcd\0\u2e10\0\u2e53\0\u0473\0\u0473\0\u0473\0\u0473"+
    "\0\u2e96\0\u2ed9\0\u2f1c\0\u2f5f\0\u0473\0\u2fa2\0\u0473\0\311"+
    "\0\u2fe5\0\u3028\0\u306b\0\u30ae\0\311\0\311\0\u30f1\0\u3134"+
    "\0\u0473\0\u3177\0\u31ba\0\u0473\0\u31fd\0\u0473\0\u3240\0\u0473"+
    "\0\u3283\0\u32c6\0\u3309\0\u334c\0\u338f\0\u33d2\0\u3415\0\311"+
    "\0\u0473\0\u3458\0\u349b\0\311\0\u34de\0\u3521\0\u3564\0\u35a7"+
    "\0\u35ea\0\u0473\0\u362d\0\u3670\0\u36b3\0\u0473\0\u36f6\0\u3739"+
    "\0\u377c\0\u0473\0\u37bf\0\u0473\0\u3802\0\u3845\0\u3888\0\u38cb"+
    "\0\u0473\0\u0473\0\u390e\0\u0473\0\u0473\0\311\0\u3951\0\u3994"+
    "\0\u0473\0\311\0\u39d7\0\u3a1a\0\u3a5d\0\u3aa0\0\311\0\u3ae3"+
    "\0\u3b26\0\u3b69\0\311\0\u3bac\0\u3bef\0\u3c32\0\u3c75\0\u3cb8"+
    "\0\u3cfb\0\u3d3e\0\u3d81\0\u0473\0\u3dc4\0\u3e07\0\311\0\u3e4a"+
    "\0\311\0\u3e8d\0\u3ed0\0\u3f13\0\311";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[341];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\3\40"+
    "\1\43\1\40\1\44\1\40\1\45\1\46\1\47\1\50"+
    "\1\51\1\40\1\52\1\53\1\54\2\40\1\55\10\40"+
    "\1\56\1\55\1\57\1\55\1\60\1\61\1\0\2\4"+
    "\76\62\1\63\2\62\1\64\1\62\22\65\1\66\5\65"+
    "\1\67\43\65\1\70\1\65\1\71\1\72\1\65\1\73"+
    "\1\66\104\0\1\74\103\0\1\75\103\0\1\76\1\77"+
    "\102\0\1\100\1\0\1\101\1\102\102\0\1\103\102\0"+
    "\1\104\103\0\1\105\103\0\1\106\120\0\1\40\1\107"+
    "\7\40\1\110\14\40\1\0\3\40\1\0\11\40\37\0"+
    "\11\40\1\111\14\40\1\0\3\40\1\0\11\40\37\0"+
    "\6\40\1\112\17\40\1\0\3\40\1\0\11\40\37\0"+
    "\1\113\25\40\1\0\3\40\1\0\11\40\37\0\5\40"+
    "\1\114\11\40\1\115\6\40\1\0\3\40\1\0\11\40"+
    "\37\0\26\40\1\0\3\40\1\0\11\40\37\0\1\116"+
    "\11\40\1\117\13\40\1\0\3\40\1\0\11\40\37\0"+
    "\10\40\1\120\15\40\1\0\3\40\1\0\11\40\37\0"+
    "\1\121\3\0\1\122\1\0\1\123\5\0\1\124\2\0"+
    "\1\125\1\0\1\126\1\0\1\127\12\0\1\130\44\0"+
    "\1\131\20\40\1\132\1\40\1\133\2\40\1\0\3\40"+
    "\1\0\11\40\37\0\11\40\1\134\14\40\1\0\3\40"+
    "\1\0\11\40\37\0\6\40\1\135\17\40\1\0\3\40"+
    "\1\0\11\40\37\0\22\40\1\136\3\40\1\0\3\40"+
    "\1\0\11\40\37\0\10\40\1\137\1\40\1\140\4\40"+
    "\1\141\6\40\1\0\3\40\1\0\11\40\37\0\5\40"+
    "\1\142\20\40\1\0\3\40\1\0\11\40\37\0\1\143"+
    "\25\40\1\0\3\40\1\0\11\40\42\0\1\144\15\0"+
    "\1\145\57\0\1\146\1\0\2\40\1\147\4\40\1\150"+
    "\1\40\1\151\3\40\1\152\6\40\1\153\1\40\1\0"+
    "\3\40\1\0\11\40\36\0\1\154\43\0\1\56\32\0"+
    "\1\155\5\0\1\156\45\0\1\157\1\160\1\0\1\161"+
    "\1\162\4\163\1\0\76\163\74\77\2\164\5\77\4\0"+
    "\1\165\125\0\2\40\1\166\23\40\1\0\3\40\1\0"+
    "\11\40\37\0\15\40\1\167\10\40\1\0\3\40\1\0"+
    "\11\40\37\0\12\40\1\170\13\40\1\0\3\40\1\0"+
    "\11\40\37\0\10\40\1\171\15\40\1\0\3\40\1\0"+
    "\11\40\37\0\4\40\1\172\15\40\1\173\3\40\1\0"+
    "\3\40\1\0\11\40\37\0\6\40\1\174\17\40\1\0"+
    "\3\40\1\0\11\40\37\0\15\40\1\175\10\40\1\0"+
    "\3\40\1\0\11\40\37\0\14\40\1\176\10\40\1\177"+
    "\1\0\3\40\1\0\11\40\37\0\24\40\1\200\1\40"+
    "\1\0\3\40\1\0\11\40\37\0\11\40\1\201\14\40"+
    "\1\0\3\40\1\0\11\40\70\0\1\202\62\0\1\203"+
    "\1\204\70\0\1\205\102\0\1\206\102\0\1\207\1\0"+
    "\1\210\1\211\3\0\1\212\1\0\1\213\2\0\1\214"+
    "\112\0\1\215\64\0\1\216\13\0\1\217\70\0\1\220"+
    "\72\0\2\40\1\221\23\40\1\0\3\40\1\0\11\40"+
    "\37\0\25\40\1\222\1\0\3\40\1\0\11\40\37\0"+
    "\21\40\1\223\4\40\1\0\3\40\1\0\11\40\37\0"+
    "\13\40\1\224\12\40\1\0\3\40\1\0\11\40\37\0"+
    "\12\40\1\225\13\40\1\0\3\40\1\0\11\40\37\0"+
    "\15\40\1\226\10\40\1\0\3\40\1\0\11\40\37\0"+
    "\6\40\1\227\17\40\1\0\3\40\1\0\11\40\37\0"+
    "\11\40\1\230\14\40\1\0\3\40\1\0\11\40\37\0"+
    "\1\231\20\40\1\232\4\40\1\0\3\40\1\0\11\40"+
    "\37\0\2\40\1\233\23\40\1\0\3\40\1\0\11\40"+
    "\37\0\1\234\126\0\1\235\77\0\1\236\61\0\26\40"+
    "\1\0\1\40\1\237\1\40\1\0\11\40\37\0\2\40"+
    "\1\240\23\40\1\0\3\40\1\0\11\40\37\0\7\40"+
    "\1\241\16\40\1\0\3\40\1\0\11\40\37\0\2\40"+
    "\1\242\23\40\1\0\3\40\1\0\11\40\37\0\1\243"+
    "\25\40\1\0\3\40\1\0\11\40\102\0\1\244\10\0"+
    "\4\163\1\245\76\163\3\0\1\246\1\165\125\0\1\247"+
    "\25\40\1\0\3\40\1\0\11\40\37\0\1\250\25\40"+
    "\1\0\3\40\1\0\11\40\37\0\17\40\1\251\6\40"+
    "\1\0\3\40\1\0\11\40\37\0\1\252\25\40\1\0"+
    "\3\40\1\0\11\40\37\0\1\253\25\40\1\0\3\40"+
    "\1\0\11\40\37\0\6\40\1\254\17\40\1\0\3\40"+
    "\1\0\11\40\37\0\14\40\1\255\11\40\1\0\3\40"+
    "\1\0\11\40\50\0\1\256\103\0\1\257\71\0\1\260"+
    "\116\0\1\261\1\0\1\262\100\0\1\263\66\0\1\264"+
    "\131\0\1\265\52\0\1\266\110\0\1\267\76\0\1\270"+
    "\100\0\1\271\116\0\1\272\107\0\1\273\61\0\1\274"+
    "\102\0\2\40\1\275\11\40\1\276\2\40\1\277\6\40"+
    "\1\0\3\40\1\0\11\40\37\0\17\40\1\300\6\40"+
    "\1\0\3\40\1\0\11\40\37\0\2\40\1\301\23\40"+
    "\1\0\3\40\1\0\11\40\37\0\3\40\1\302\22\40"+
    "\1\0\3\40\1\0\11\40\37\0\21\40\1\303\4\40"+
    "\1\0\3\40\1\0\11\40\37\0\15\40\1\304\10\40"+
    "\1\0\3\40\1\0\11\40\37\0\1\40\1\305\24\40"+
    "\1\0\3\40\1\0\11\40\37\0\11\40\1\306\14\40"+
    "\1\0\3\40\1\0\11\40\37\0\2\40\1\307\11\40"+
    "\1\310\2\40\1\311\6\40\1\0\3\40\1\0\11\40"+
    "\61\0\1\312\74\0\1\313\67\0\1\314\101\0\2\40"+
    "\1\315\23\40\1\0\3\40\1\0\11\40\37\0\12\40"+
    "\1\316\13\40\1\0\3\40\1\0\11\40\37\0\11\40"+
    "\1\317\14\40\1\0\3\40\1\0\11\40\37\0\6\40"+
    "\1\320\17\40\1\0\3\40\1\0\11\40\37\0\1\40"+
    "\1\321\24\40\1\0\3\40\1\0\11\40\10\0\4\163"+
    "\1\245\1\163\1\164\74\163\4\0\1\164\125\0\26\40"+
    "\1\0\3\40\1\322\11\40\37\0\10\40\1\323\15\40"+
    "\1\0\3\40\1\0\11\40\37\0\17\40\1\324\6\40"+
    "\1\0\3\40\1\0\11\40\37\0\1\325\25\40\1\0"+
    "\3\40\1\0\11\40\37\0\1\326\25\40\1\0\3\40"+
    "\1\0\11\40\54\0\1\327\102\0\1\330\71\0\1\331"+
    "\76\0\1\332\105\0\1\333\111\0\1\334\72\0\1\335"+
    "\102\0\1\336\104\0\1\337\117\0\1\340\73\0\1\341"+
    "\71\0\1\342\103\0\1\343\116\0\1\344\64\0\1\345"+
    "\25\40\1\0\3\40\1\0\11\40\37\0\12\40\1\346"+
    "\13\40\1\0\3\40\1\0\11\40\37\0\1\40\1\347"+
    "\7\40\1\350\14\40\1\0\3\40\1\0\11\40\37\0"+
    "\4\40\1\351\21\40\1\0\3\40\1\0\11\40\37\0"+
    "\17\40\1\352\6\40\1\0\3\40\1\0\11\40\37\0"+
    "\12\40\1\353\13\40\1\0\3\40\1\0\11\40\37\0"+
    "\1\354\25\40\1\0\3\40\1\0\11\40\37\0\1\355"+
    "\25\40\1\0\3\40\1\0\11\40\37\0\1\356\25\40"+
    "\1\0\3\40\1\0\11\40\37\0\12\40\1\357\13\40"+
    "\1\0\3\40\1\0\11\40\37\0\1\40\1\360\7\40"+
    "\1\361\14\40\1\0\3\40\1\0\11\40\60\0\1\362"+
    "\73\0\1\363\111\0\1\364\61\0\1\40\1\365\12\40"+
    "\1\366\2\40\1\367\6\40\1\0\3\40\1\0\11\40"+
    "\37\0\1\40\1\370\24\40\1\0\3\40\1\0\11\40"+
    "\37\0\21\40\1\371\4\40\1\0\3\40\1\0\11\40"+
    "\37\0\15\40\1\372\10\40\1\0\3\40\1\0\11\40"+
    "\60\0\1\373\61\0\11\40\1\374\14\40\1\0\3\40"+
    "\1\0\11\40\37\0\2\40\1\375\23\40\1\0\3\40"+
    "\1\0\11\40\37\0\15\40\1\376\10\40\1\0\3\40"+
    "\1\0\11\40\37\0\6\40\1\377\17\40\1\0\3\40"+
    "\1\0\11\40\37\0\1\u0100\110\0\1\u0101\77\0\1\u0102"+
    "\105\0\1\u0103\107\0\1\u0104\72\0\1\u0105\77\0\1\u0106"+
    "\114\0\1\u0107\70\0\26\40\1\0\1\40\1\u0108\1\40"+
    "\1\0\11\40\37\0\15\40\1\u0109\10\40\1\0\3\40"+
    "\1\0\11\40\37\0\4\40\1\u010a\21\40\1\0\3\40"+
    "\1\0\11\40\37\0\2\40\1\u010b\23\40\1\0\3\40"+
    "\1\0\11\40\37\0\5\40\1\u010c\20\40\1\0\3\40"+
    "\1\0\11\40\37\0\6\40\1\u010d\17\40\1\0\3\40"+
    "\1\0\11\40\37\0\1\40\1\u010e\24\40\1\0\3\40"+
    "\1\0\11\40\37\0\26\40\1\0\1\40\1\u010f\1\40"+
    "\1\0\11\40\37\0\15\40\1\u0110\10\40\1\0\3\40"+
    "\1\0\11\40\37\0\4\40\1\u0111\21\40\1\0\3\40"+
    "\1\0\11\40\37\0\2\40\1\u0112\23\40\1\0\3\40"+
    "\1\0\11\40\40\0\1\u0113\107\0\1\u0114\100\0\1\u0115"+
    "\76\0\1\40\1\u0116\24\40\1\0\3\40\1\0\11\40"+
    "\37\0\17\40\1\u0117\6\40\1\0\3\40\1\0\11\40"+
    "\61\0\1\u0118\60\0\2\40\1\u0119\23\40\1\0\3\40"+
    "\1\0\11\40\37\0\17\40\1\u011a\6\40\1\0\3\40"+
    "\1\0\11\40\55\0\1\u011b\64\0\1\u011c\115\0\1\u011d"+
    "\124\0\1\u011e\60\0\1\u011f\67\0\2\40\1\u0120\23\40"+
    "\1\0\3\40\1\0\11\40\37\0\5\40\1\u0121\20\40"+
    "\1\0\3\40\1\0\11\40\37\0\12\40\1\u0122\13\40"+
    "\1\0\3\40\1\0\11\40\37\0\13\40\1\u0123\12\40"+
    "\1\0\3\40\1\0\11\40\37\0\2\40\1\u0124\23\40"+
    "\1\0\3\40\1\0\11\40\37\0\5\40\1\u0125\20\40"+
    "\1\0\3\40\1\0\11\40\37\0\12\40\1\u0126\13\40"+
    "\1\0\3\40\1\0\11\40\60\0\1\u0127\63\0\1\u0128"+
    "\121\0\1\u0129\61\0\25\40\1\u012a\1\0\3\40\1\0"+
    "\11\40\37\0\26\40\1\0\3\40\1\0\1\u012b\10\40"+
    "\37\0\6\40\1\u012c\17\40\1\0\3\40\1\0\11\40"+
    "\56\0\1\u012d\101\0\1\u012e\77\0\1\u012f\126\0\1\u0130"+
    "\43\0\12\40\1\u0131\13\40\1\0\3\40\1\0\11\40"+
    "\37\0\12\40\1\u0132\13\40\1\0\3\40\1\0\11\40"+
    "\37\0\4\40\1\u0133\21\40\1\0\3\40\1\0\11\40"+
    "\37\0\12\40\1\u0134\13\40\1\0\3\40\1\0\11\40"+
    "\37\0\12\40\1\u0135\13\40\1\0\3\40\1\0\11\40"+
    "\45\0\1\u0136\113\0\1\u0137\102\0\1\u0138\63\0\1\u0139"+
    "\25\40\1\0\3\40\1\0\11\40\45\0\1\u013a\74\0"+
    "\1\u013b\121\0\1\u013c\123\0\1\u013d\42\0\11\40\1\u013e"+
    "\14\40\1\0\3\40\1\0\11\40\45\0\1\u013f\102\0"+
    "\1\u0140\75\0\1\u0141\102\0\1\u0142\142\0\1\u0143\41\0"+
    "\21\40\1\u0144\4\40\1\0\3\40\1\0\11\40\52\0"+
    "\1\u0145\71\0\1\u0146\104\0\1\u0147\76\0\4\40\1\u0148"+
    "\21\40\1\0\3\40\1\0\11\40\55\0\1\u0149\103\0"+
    "\1\u014a\70\0\1\u014b\75\0\26\40\1\0\3\40\1\0"+
    "\1\40\1\u014c\7\40\37\0\1\u014d\103\0\1\u014e\113\0"+
    "\1\u014f\71\0\1\u0150\120\0\1\u0151\65\0\1\u0152\117\0"+
    "\1\u0153\64\0\1\u0154\120\0\1\u0155\34\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[16214];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\2\1\1\11\6\1\15\11\22\1\1\11"+
    "\1\1\5\11\1\1\11\11\1\0\1\1\1\0\6\11"+
    "\12\1\10\0\13\1\3\0\5\1\1\0\6\11\1\0"+
    "\1\11\1\0\14\1\15\0\1\11\1\0\13\1\3\0"+
    "\6\1\2\0\7\1\14\0\1\11\2\0\15\1\3\0"+
    "\5\1\1\0\4\1\1\11\1\0\1\11\1\0\1\11"+
    "\1\0\3\11\5\0\15\1\3\0\6\1\1\0\4\1"+
    "\1\11\4\0\2\11\1\0\13\1\3\0\2\1\1\11"+
    "\2\1\1\0\1\11\3\0\7\1\3\0\3\1\4\0"+
    "\5\1\1\11\2\0\1\1\1\11\3\0\1\1\1\11"+
    "\3\0\1\11\1\1\3\0\1\1\3\0\1\1\2\0"+
    "\1\11\1\0\1\11\3\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[341];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //Código de usuario
    String tempcadena= "";
    int escape = 0;
    int contador = 0;



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 206) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { String errLex = "Error léxico : '"+yytext()+"' en la línea: "+(yyline+1)+" y columna: "+(yycolumn+1);
        System.out.println(errLex);
            } 
            // fall through
          case 111: break;
          case 2: 
            { return new Symbol(sym.Tmenos, yyline, yycolumn,yytext());
            } 
            // fall through
          case 112: break;
          case 3: 
            { return new Symbol(sym.Tmas, yyline, yycolumn,yytext());
            } 
            // fall through
          case 113: break;
          case 4: 
            { return new Symbol(sym.Tpor, yyline, yycolumn,yytext());
            } 
            // fall through
          case 114: break;
          case 5: 
            { return new Symbol(sym.Tdiv, yyline, yycolumn,yytext());
            } 
            // fall through
          case 115: break;
          case 6: 
            { return new Symbol(sym.Tmenor, yyline, yycolumn,yytext());
            } 
            // fall through
          case 116: break;
          case 7: 
            { return new Symbol(sym.Tmayor, yyline, yycolumn,yytext());
            } 
            // fall through
          case 117: break;
          case 8: 
            { return new Symbol(sym.Tigual, yyline, yycolumn,yytext());
            } 
            // fall through
          case 118: break;
          case 9: 
            { return new Symbol(sym.Tllave_a, yyline, yycolumn,yytext());
            } 
            // fall through
          case 119: break;
          case 10: 
            { return new Symbol(sym.Tllave_c, yyline, yycolumn,yytext());
            } 
            // fall through
          case 120: break;
          case 11: 
            { return new Symbol(sym.Tcorchete_a, yyline, yycolumn,yytext());
            } 
            // fall through
          case 121: break;
          case 12: 
            { return new Symbol(sym.Tcorchete_c, yyline, yycolumn,yytext());
            } 
            // fall through
          case 122: break;
          case 13: 
            { return new Symbol(sym.Tpycoma, yyline, yycolumn,yytext());
            } 
            // fall through
          case 123: break;
          case 14: 
            { return new Symbol(sym.Tpar_a, yyline, yycolumn,yytext());
            } 
            // fall through
          case 124: break;
          case 15: 
            { return new Symbol(sym.Tpar_c, yyline, yycolumn,yytext());
            } 
            // fall through
          case 125: break;
          case 16: 
            { return new Symbol(sym.Tcoma, yyline, yycolumn,yytext());
            } 
            // fall through
          case 126: break;
          case 17: 
            { return new Symbol(sym.Tmod, yyline, yycolumn,yytext());
            } 
            // fall through
          case 127: break;
          case 18: 
            { return new Symbol(sym.Tnot, yyline, yycolumn,yytext());
            } 
            // fall through
          case 128: break;
          case 19: 
            { return new Symbol(sym.Tpotencia, yyline, yycolumn,yytext());
            } 
            // fall through
          case 129: break;
          case 20: 
            { return new Symbol(sym.Tdospuntos, yyline, yycolumn,yytext());
            } 
            // fall through
          case 130: break;
          case 21: 
            { return new Symbol(sym.Tpunto, yyline, yycolumn,yytext());
            } 
            // fall through
          case 131: break;
          case 22: 
            { return new Symbol(sym.Tid, yyline, yycolumn,yytext());
            } 
            // fall through
          case 132: break;
          case 23: 
            { /*Espacios en blanco, ignorados*/
            } 
            // fall through
          case 133: break;
          case 24: 
            { return new Symbol(sym.Tentero, yyline, yycolumn,yytext());
            } 
            // fall through
          case 134: break;
          case 25: 
            { /*Saltos de linea, ignorados*/
            } 
            // fall through
          case 135: break;
          case 26: 
            { yybegin(cadena);
            } 
            // fall through
          case 136: break;
          case 27: 
            { yybegin(cadena2); tempcadena+="\'"; escape=0; contador=0;
            } 
            // fall through
          case 137: break;
          case 28: 
            { tempcadena+=yytext();
            } 
            // fall through
          case 138: break;
          case 29: 
            { String temp=tempcadena; tempcadena=""; yybegin(YYINITIAL); return  new Symbol(sym.Tcadena, yychar,yyline, temp);
            } 
            // fall through
          case 139: break;
          case 30: 
            { contador++; tempcadena+=yytext();
            } 
            // fall through
          case 140: break;
          case 31: 
            { contador++;
                if(escape==0){
                    tempcadena+=yytext();              
                }else{
                 tempcadena+=yytext();
                 escape=0;
                }
            } 
            // fall through
          case 141: break;
          case 32: 
            { contador++;
                if(escape==0){
                 tempcadena+=yytext();
                }else{
                 tempcadena+=yytext();
                 escape=0;
                }
            } 
            // fall through
          case 142: break;
          case 33: 
            { if(escape==0){
                    String tmp=tempcadena; tempcadena="";  
                    System.out.println("Se esperaba cierre de caracter (\")."); 
                    yybegin(YYINITIAL);
                }else{
                    String tmp=tempcadena; tempcadena="";  
                    System.out.println("Se esperaba caracter de escape o cierre de caracter;"); 
                    yybegin(YYINITIAL); 
                }
            } 
            // fall through
          case 143: break;
          case 34: 
            { if(escape==0){
                    String tmp=tempcadena; tempcadena="";  
                    System.out.println("Caracter especial  sin escape definido"); 
                    yybegin(YYINITIAL);              
                }else{
                 tempcadena+=yytext();
                 escape=0;
                 contador++;
                }
            } 
            // fall through
          case 144: break;
          case 35: 
            { if(escape==0){
                    if(contador>=1)
                    {
                        String tmp=tempcadena+"\'"; 
                        tempcadena=""; yybegin(YYINITIAL);  
                        return new Symbol(sym.Tcaracter, yychar,yyline,tmp); 
                    }
                    else{
                        String tmp=tempcadena; tempcadena="";  
                        System.out.println("Tipo de dato caracter tiene mas de 1 caracter"); 
                        yybegin(YYINITIAL);
                    }
                }
                else{
                    tempcadena+=yytext();
                    escape=0;
                    contador++;
                }
            } 
            // fall through
          case 145: break;
          case 36: 
            { tempcadena+=yytext();
                if(escape==0){
                 escape=1;
                }else{
                 escape=0;
                 contador++;
                }
            } 
            // fall through
          case 146: break;
          case 37: 
            { return new Symbol(sym.Tdecremento, yyline, yycolumn,yytext());
            } 
            // fall through
          case 147: break;
          case 38: 
            { return new Symbol(sym.Tincremento, yyline, yycolumn,yytext());
            } 
            // fall through
          case 148: break;
          case 39: 
            { /*iognore*/
            } 
            // fall through
          case 149: break;
          case 40: 
            { return new Symbol(sym.Tdiferente, yyline, yycolumn,yytext());
            } 
            // fall through
          case 150: break;
          case 41: 
            { return new Symbol(sym.Tmenorigual, yyline, yycolumn,yytext());
            } 
            // fall through
          case 151: break;
          case 42: 
            { return new Symbol(sym.Tmayorigual, yyline, yycolumn,yytext());
            } 
            // fall through
          case 152: break;
          case 43: 
            { return new Symbol(sym.Tigualigual, yyline, yycolumn,yytext());
            } 
            // fall through
          case 153: break;
          case 44: 
            { return new Symbol(sym.Tor, yyline, yycolumn,yytext());
            } 
            // fall through
          case 154: break;
          case 45: 
            { return new Symbol(sym.Tand, yyline, yycolumn,yytext());
            } 
            // fall through
          case 155: break;
          case 46: 
            { return new Symbol(sym.Tif, yyline, yycolumn,yytext());
            } 
            // fall through
          case 156: break;
          case 47: 
            { tempcadena+='%';
            } 
            // fall through
          case 157: break;
          case 48: 
            { tempcadena+='\n';
            } 
            // fall through
          case 158: break;
          case 49: 
            { tempcadena+='\"';
            } 
            // fall through
          case 159: break;
          case 50: 
            { tempcadena+='\'';
            } 
            // fall through
          case 160: break;
          case 51: 
            { tempcadena+='\\';
            } 
            // fall through
          case 161: break;
          case 52: 
            { tempcadena+='?';
            } 
            // fall through
          case 162: break;
          case 53: 
            { return new Symbol(sym.Tent, yyline, yycolumn,yytext());
            } 
            // fall through
          case 163: break;
          case 54: 
            { return new Symbol(sym.Tnlo, yyline, yycolumn,yytext());
            } 
            // fall through
          case 164: break;
          case 55: 
            { return new Symbol(sym.Tdec, yyline, yycolumn,yytext());
            } 
            // fall through
          case 165: break;
          case 56: 
            { return new Symbol(sym.Tchr, yyline, yycolumn,yytext());
            } 
            // fall through
          case 166: break;
          case 57: 
            { return new Symbol(sym.Tbul, yyline, yycolumn,yytext());
            } 
            // fall through
          case 167: break;
          case 58: 
            { return new Symbol(sym.Twf, yyline, yycolumn,yytext());
            } 
            // fall through
          case 168: break;
          case 59: 
            { return new Symbol(sym.Tzro, yyline, yycolumn,yytext());
            } 
            // fall through
          case 169: break;
          case 60: 
            { return new Symbol(sym.Tfor, yyline, yycolumn,yytext());
            } 
            // fall through
          case 170: break;
          case 61: 
            { return new Symbol(sym.Tdecimal, yyline, yycolumn,yytext());
            } 
            // fall through
          case 171: break;
          case 62: 
            { return new Symbol(sym.Telse, yyline, yycolumn,yytext());
            } 
            // fall through
          case 172: break;
          case 63: 
            { return new Symbol(sym.Ttrue, yyline, yycolumn,yytext());
            } 
            // fall through
          case 173: break;
          case 64: 
            { return new Symbol(sym.Tcase, yyline, yycolumn,yytext());
            } 
            // fall through
          case 174: break;
          case 65: 
            { return new Symbol(sym.Timp, yyline, yycolumn,yytext());
            } 
            // fall through
          case 175: break;
          case 66: 
            { return new Symbol(sym.Tsiga, yyline, yycolumn,yytext());
            } 
            // fall through
          case 176: break;
          case 67: 
            { return new Symbol(sym.Twhen, yyline, yycolumn,yytext());
            } 
            // fall through
          case 177: break;
          case 68: 
            { return new Symbol(sym.Trtxt, yyline, yycolumn,yytext());
            } 
            // fall through
          case 178: break;
          case 69: 
            { return new Symbol(sym.Tlbl, yyline, yycolumn,yytext());
            } 
            // fall through
          case 179: break;
          case 70: 
            { return new Symbol(sym.Teqls, yyline, yycolumn,yytext());
            } 
            // fall through
          case 180: break;
          case 71: 
            { return new Symbol(sym.Tconc, yyline, yycolumn,yytext());
            } 
            // fall through
          case 181: break;
          case 72: 
            { return new Symbol(sym.Tread, yyline, yycolumn,yytext());
            } 
            // fall through
          case 182: break;
          case 73: 
            { return new Symbol(sym.Taent, yyline, yycolumn,yytext());
            } 
            // fall through
          case 183: break;
          case 74: 
            { return new Symbol(sym.Tatxt, yyline, yycolumn,yytext());
            } 
            // fall through
          case 184: break;
          case 75: 
            { return new Symbol(sym.Tadec, yyline, yycolumn,yytext());
            } 
            // fall through
          case 185: break;
          case 76: 
            { return new Symbol(sym.Tfalse, yyline, yycolumn,yytext());
            } 
            // fall through
          case 186: break;
          case 77: 
            { return new Symbol(sym.Twhile, yyline, yycolumn,yytext());
            } 
            // fall through
          case 187: break;
          case 78: 
            { return new Symbol(sym.Trtxtn, yyline, yycolumn,yytext());
            } 
            // fall through
          case 188: break;
          case 79: 
            { return new Symbol(sym.Trtxtp, yyline, yycolumn,yytext());
            } 
            // fall through
          case 189: break;
          case 80: 
            { return new Symbol(sym.Trtxta, yyline, yycolumn,yytext());
            } 
            // fall through
          case 190: break;
          case 81: 
            { return new Symbol(sym.Trbton, yyline, yycolumn,yytext());
            } 
            // fall through
          case 191: break;
          case 82: 
            { return new Symbol(sym.Trepeat, yyline, yycolumn,yytext());
            } 
            // fall through
          case 192: break;
          case 83: 
            { return new Symbol(sym.Tromper, yyline, yycolumn,yytext());
            } 
            // fall through
          case 193: break;
          case 84: 
            { return new Symbol(sym.Tclose, yyline, yycolumn,yytext());
            } 
            // fall through
          case 194: break;
          case 85: 
            { return new Symbol(sym.Tapend, yyline, yycolumn,yytext());
            } 
            // fall through
          case 195: break;
          case 86: 
            { return new Symbol(sym.Twrite, yyline, yycolumn,yytext());
            } 
            // fall through
          case 196: break;
          case 87: 
            { return new Symbol(sym.Tsetpos, yyline, yycolumn,yytext());
            } 
            // fall through
          case 197: break;
          case 88: 
            { return new Symbol(sym.Tswitch, yyline, yycolumn,yytext());
            } 
            // fall through
          case 198: break;
          case 89: 
            { return new Symbol(sym.Tfusion, yyline, yycolumn,yytext());
            } 
            // fall through
          case 199: break;
          case 90: 
            { return new Symbol(sym.Tgetpos, yyline, yycolumn,yytext());
            } 
            // fall through
          case 200: break;
          case 91: 
            { return new Symbol(sym.Telseif, yyline, yycolumn,yytext());
            } 
            // fall through
          case 201: break;
          case 92: 
            { return new Symbol(sym.Tdefault, yyline, yycolumn,yytext());
            } 
            // fall through
          case 202: break;
          case 93: 
            { return new Symbol(sym.Tpesode, yyline, yycolumn,yytext());
            } 
            // fall through
          case 203: break;
          case 94: 
            { return new Symbol(sym.Tsetalto, yyline, yycolumn,yytext());
            } 
            // fall through
          case 204: break;
          case 95: 
            { return new Symbol(sym.Tgetalto, yyline, yycolumn,yytext());
            } 
            // fall through
          case 205: break;
          case 96: 
            { return new Symbol(sym.Trstring, yyline, yycolumn,yytext());
            } 
            // fall through
          case 206: break;
          case 97: 
            { return new Symbol(sym.Tregresar, yyline, yycolumn,yytext());
            } 
            // fall through
          case 207: break;
          case 98: 
            { return new Symbol(sym.Tsettexto, yyline, yycolumn,yytext());
            } 
            // fall through
          case 208: break;
          case 99: 
            { return new Symbol(sym.Tsetancho, yyline, yycolumn,yytext());
            } 
            // fall through
          case 209: break;
          case 100: 
            { return new Symbol(sym.Tgettexto, yyline, yycolumn,yytext());
            } 
            // fall through
          case 210: break;
          case 101: 
            { return new Symbol(sym.Tgetancho, yyline, yycolumn,yytext());
            } 
            // fall through
          case 211: break;
          case 102: 
            { return new Symbol(sym.Tdefinir, yyline, yycolumn,yytext());
            } 
            // fall through
          case 212: break;
          case 103: 
            { return new Symbol(sym.Trmensage, yyline, yycolumn,yytext());
            } 
            // fall through
          case 213: break;
          case 104: 
            { return new Symbol(sym.Treservar, yyline, yycolumn,yytext());
            } 
            // fall through
          case 214: break;
          case 105: 
            { return new Symbol(sym.Timportar, yyline, yycolumn,yytext());
            } 
            // fall through
          case 215: break;
          case 106: 
            { return new Symbol(sym.Tnuevogui, yyline, yycolumn,yytext());
            } 
            // fall through
          case 216: break;
          case 107: 
            { return new Symbol(sym.Taldarclick, yyline, yycolumn,yytext());
            } 
            // fall through
          case 217: break;
          case 108: 
            { return new Symbol(sym.Taltoyancho, yyline, yycolumn,yytext());
            } 
            // fall through
          case 218: break;
          case 109: 
            { return new Symbol(sym.Tabrirventana, yyline, yycolumn,yytext());
            } 
            // fall through
          case 219: break;
          case 110: 
            { return new Symbol(sym.Tiniciarventana, yyline, yycolumn,yytext());
            } 
            // fall through
          case 220: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
