
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Twhile = 39;
  public static final int Twhen = 51;
  public static final int Tpor = 4;
  public static final int Tcoma = 20;
  public static final int Taent = 56;
  public static final int Tgettexto = 81;
  public static final int Tigualigual = 8;
  public static final int Tincremento = 27;
  public static final int Tmenos = 2;
  public static final int Ttrue = 52;
  public static final int Tmenor = 9;
  public static final int Tnot = 24;
  public static final int Tpotencia = 25;
  public static final int Teqls = 58;
  public static final int Trepeat = 41;
  public static final int Truta = 88;
  public static final int Tdec = 31;
  public static final int Tcorchete_c = 16;
  public static final int Tcorchete_a = 15;
  public static final int Tpunto = 29;
  public static final int Tapend = 63;
  public static final int Tpesode = 35;
  public static final int Tsetancho = 78;
  public static final int Tromper = 45;
  public static final int Tcadena = 96;
  public static final int Telse = 59;
  public static final int Tdecremento = 28;
  public static final int Tmod = 21;
  public static final int Tdiferente = 6;
  public static final int Trstring = 98;
  public static final int Tsetalto = 79;
  public static final int Tzro = 37;
  public static final int Taltoyancho = 76;
  public static final int Tfechamod = 92;
  public static final int Tlbl = 67;
  public static final int Treservar = 36;
  public static final int Tmenorigual = 23;
  public static final int Tfor = 40;
  public static final int Tdiv = 5;
  public static final int Tgetalto = 83;
  public static final int Trtxt = 68;
  public static final int Timportar = 49;
  public static final int Tmas = 3;
  public static final int Trtxtp = 70;
  public static final int Tllave_c = 14;
  public static final int Tnuevogui = 85;
  public static final int Trtxtn = 71;
  public static final int Tllave_a = 13;
  public static final int Taldarclick = 75;
  public static final int Tgetancho = 82;
  public static final int Twf = 64;
  public static final int Tdecimal = 94;
  public static final int Tcase = 43;
  public static final int Trtxta = 69;
  public static final int Tpycoma = 17;
  public static final int Tconfiguracion = 91;
  public static final int Tbul = 33;
  public static final int Tent = 30;
  public static final int Tclose = 65;
  public static final int CONCAT = 99;
  public static final int Tdospuntos = 26;
  public static final int Tdefinir = 47;
  public static final int Tcarpeta = 89;
  public static final int Tchr = 32;
  public static final int Timp = 61;
  public static final int Telseif = 60;
  public static final int Tnlo = 34;
  public static final int EOF = 0;
  public static final int Tsiga = 46;
  public static final int Tadec = 57;
  public static final int Tmayor = 10;
  public static final int Tdefault = 44;
  public static final int Tmayorigual = 22;
  public static final int Tcaracter = 97;
  public static final int Tread = 66;
  public static final int Tarchivo = 87;
  public static final int Tor = 11;
  public static final int error = 1;
  public static final int Tiniciarventana = 74;
  public static final int Tsettexto = 77;
  public static final int Tentero = 95;
  public static final int Tand = 12;
  public static final int Tsetpos = 80;
  public static final int Tif = 38;
  public static final int Tid = 93;
  public static final int Tfalse = 53;
  public static final int Trmensage = 73;
  public static final int Tregresar = 50;
  public static final int Tcorrer = 90;
  public static final int Tgetpos = 84;
  public static final int Tconc = 55;
  public static final int Trbton = 72;
  public static final int Tfusion = 48;
  public static final int Tproyecto = 86;
  public static final int Twrite = 62;
  public static final int Tatxt = 54;
  public static final int Tswitch = 42;
  public static final int Tpar_c = 19;
  public static final int Tigual = 7;
  public static final int Tpar_a = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Tmenos",
  "Tmas",
  "Tpor",
  "Tdiv",
  "Tdiferente",
  "Tigual",
  "Tigualigual",
  "Tmenor",
  "Tmayor",
  "Tor",
  "Tand",
  "Tllave_a",
  "Tllave_c",
  "Tcorchete_a",
  "Tcorchete_c",
  "Tpycoma",
  "Tpar_a",
  "Tpar_c",
  "Tcoma",
  "Tmod",
  "Tmayorigual",
  "Tmenorigual",
  "Tnot",
  "Tpotencia",
  "Tdospuntos",
  "Tincremento",
  "Tdecremento",
  "Tpunto",
  "Tent",
  "Tdec",
  "Tchr",
  "Tbul",
  "Tnlo",
  "Tpesode",
  "Treservar",
  "Tzro",
  "Tif",
  "Twhile",
  "Tfor",
  "Trepeat",
  "Tswitch",
  "Tcase",
  "Tdefault",
  "Tromper",
  "Tsiga",
  "Tdefinir",
  "Tfusion",
  "Timportar",
  "Tregresar",
  "Twhen",
  "Ttrue",
  "Tfalse",
  "Tatxt",
  "Tconc",
  "Taent",
  "Tadec",
  "Teqls",
  "Telse",
  "Telseif",
  "Timp",
  "Twrite",
  "Tapend",
  "Twf",
  "Tclose",
  "Tread",
  "Tlbl",
  "Trtxt",
  "Trtxta",
  "Trtxtp",
  "Trtxtn",
  "Trbton",
  "Trmensage",
  "Tiniciarventana",
  "Taldarclick",
  "Taltoyancho",
  "Tsettexto",
  "Tsetancho",
  "Tsetalto",
  "Tsetpos",
  "Tgettexto",
  "Tgetancho",
  "Tgetalto",
  "Tgetpos",
  "Tnuevogui",
  "Tproyecto",
  "Tarchivo",
  "Truta",
  "Tcarpeta",
  "Tcorrer",
  "Tconfiguracion",
  "Tfechamod",
  "Tid",
  "Tdecimal",
  "Tentero",
  "Tcadena",
  "Tcaracter",
  "Trstring",
  "CONCAT"
  };
}

