/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Instrucciones;

/**
 *
 * @author Andree
 */
public enum Tipo {
    //region Tipos Sentencias
    WHILE, IF, BREAK, DOWHILE, FOR, FUNCION, METODO,
    ASIGNACION, DECLARACION, IMPRIMIR, OPERACION,
    RETURN, SWITCH, OPERADOR, VARIABLE, CONSTANTE,
    DEFINIR, LLAMADA, REFERENCIA, FUSION,
    DECLARACION_FUSION, ASIGNACION_FUSION,
    DEF_STRUCT, OBJETO, SEGUIR,
    //endregion

    Entero, Decimal, Cadena, Char, Bool, Identificador, COMPONENTE,
    Struct, String, ASIGNACION_ARREGLO, ARREGLO, ARREGLO_SIMPLE_DECLARACION, DECLARACION_ARREGLO, ELSE_IF,
    LABEL, TEXTBOX, TEXTAREA, TEXTPASSWORD, TEXTNUMERO, BUTTON, MENSAJE,
    ETIQUETA_SIGUE, ETIQUETA_ROMPE, ETIQUETA_RETURN, SENTENCIA_SWITCH,
    INCREMENTO, DECREMENTO, CONCATENACION, IMPORTAR, WRITE, CLOSE, APEND,
    READ, INICIO_VENTANA, VENTANA, ABRIR_VENTANA, Frame, DECLARACION_COMPONENTE,
    ASIGNACION_COMPONENTE, DESPLEGAR_MENSAJE, ANCHO_ALTO, SETTEXT, SET_ANCHO, SET_ALTO, SET_POS, EVENTO_CLICK, EVENTO

    //
}
